### ISSUE TITLE
Determine to upgrade or use which analytics service

### ISSUE THREAD

**Issue by mhaidarhanif** [bandungpy/pycon.id#33]
Since Vercel Analytics for https://pycon.id has reached its free limit due to a large number of visitors.

Next up, either we have to upgrade it. Or it can be replaced with either an analytics service like Google Analytics or Microsoft Clarity https://clarity.microsoft.com. However, there is a tradeoff between privacy and the simplicity of the data.

Alternatively, we can consider self-hosting an open-source solution like Plausible https://github.com/plausible/analytics or Umami https://github.com/umami-software/umami so it can be run forever.

**Comment by ridhof** [comment]
Umami has Umami Cloud which doesn't require us to self-host the Umami Instance, and its pricing its pretty more advantageous for us compared to Vercel Analytics

[Umami Cloud Free Tier](https://umami.is/pricing) has 10k monthly events 
[Vercel Analytics Free Tier](https://vercel.com/pricing) has 2.5k monthly events

We could try analytics service that doesn't require us to host by ourself since both FE and BE team are pretty busy around this time.

Fanthom is pretty popular, but it has no free tier.
Plenty alternatives doesn't have any free tier too.

**Comment by mhaidarhanif** [comment]
Umami Cloud looks nice then. Let's use it. But still keep both to see which one is the best.

cc @bandungpy/frontend
